import {
  SiCss,
  SiExpress,
  SiGit,
  SiHtml5,
  SiJavascript,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiPython,
  SiReact,
  SiTailwindcss,
  SiVercel,
  SiVscodium,
} from 'react-icons/si';

export const TECHNOLOGIES = [
  {
    id: 'vscode',
    label: 'VS Code',
    color: '#3B82F6',
    Icon: SiVscodium,
    shell: 'outer',
  },
  {
    id: 'git',
    label: 'Git',
    color: '#F97316',
    Icon: SiGit,
    shell: 'middle',
  },
  {
    id: 'linux',
    label: 'Linux',
    color: '#FB7185',
    Icon: SiLinux,
    shell: 'outer',
  },
  {
    id: 'vercel',
    label: 'Vercel',
    color: '#F8FAFC',
    Icon: SiVercel,
    shell: 'outer',
  },
  {
    id: 'python',
    label: 'Python',
    color: '#A78BFA',
    Icon: SiPython,
    shell: 'middle',
  },
  {
    id: 'sql',
    label: 'SQL',
    color: '#818CF8',
    Icon: SiMysql,
    shell: 'inner',
  },
  {
    id: 'react',
    label: 'React',
    color: '#61DAFB',
    Icon: SiReact,
    shell: 'outer',
  },
  {
    id: 'html',
    label: 'HTML5',
    color: '#F97316',
    Icon: SiHtml5,
    shell: 'middle',
  },
  {
    id: 'css',
    label: 'CSS3',
    color: '#38BDF8',
    Icon: SiCss,
    shell: 'middle',
  },
  {
    id: 'next',
    label: 'Next.js',
    color: '#E2E8F0',
    Icon: SiNextdotjs,
    shell: 'middle',
  },
  {
    id: 'tailwind',
    label: 'Tailwind',
    color: '#38BDF8',
    Icon: SiTailwindcss,
    shell: 'outer',
  },
  {
    id: 'node',
    label: 'Node.js',
    color: '#4ADE80',
    Icon: SiNodedotjs,
    shell: 'inner',
  },
  {
    id: 'mongodb',
    label: 'MongoDB',
    color: '#34D399',
    Icon: SiMongodb,
    shell: 'inner',
  },
  {
    id: 'express',
    label: 'Express',
    color: '#CBD5E1',
    Icon: SiExpress,
    shell: 'inner',
  },
  {
    id: 'javascript',
    label: 'JavaScript',
    color: '#FACC15',
    Icon: SiJavascript,
    shell: 'middle',
  },
];

export const ORBIT_SHELLS = [
  {
    id: 'inner',
    radius: '5.85rem',
    duration: '18s',
    direction: 'normal',
  },
  {
    id: 'middle',
    radius: '8.45rem',
    duration: '25s',
    direction: 'reverse',
  },
  {
    id: 'outer',
    radius: '10.75rem',
    duration: '33s',
    direction: 'normal',
  },
];
